"""Initial migration

Revision ID: aa75a0770c97
Revises: 
Create Date: 2026-01-02 22:02:11.173785

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'aa75a0770c97'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_name'), 'asset', ['name'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('before_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('after_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_table('job_execution_logs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=True),
    sa.Column('process_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('machine_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('host_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('host_identity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_execution_logs_created_at'), 'job_execution_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_execution_logs_job_execution_id'), 'job_execution_logs', ['job_execution_id'], unique=False)
    op.create_index('ix_job_execution_logs_job_execution_id_level', 'job_execution_logs', ['job_execution_id', 'level'], unique=False)
    op.create_index('ix_job_execution_logs_job_execution_id_timestamp', 'job_execution_logs', ['job_execution_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_job_execution_logs_level'), 'job_execution_logs', ['level'], unique=False)
    op.create_index(op.f('ix_job_execution_logs_timestamp'), 'job_execution_logs', ['timestamp'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('package_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('package_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('entrypoint_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queue_item_ids', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parameters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logs_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('started_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('finished_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_execution_id'), 'jobs', ['execution_id'], unique=True)
    op.create_index(op.f('ix_jobs_source'), 'jobs', ['source'], unique=False)
    op.create_index(op.f('ix_jobs_trigger_id'), 'jobs', ['trigger_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_seen_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('machine_key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('signature_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_name'), 'machines', ['name'], unique=True)
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('scripts_manifest', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_bvpackage', sa.Boolean(), nullable=False),
    sa.Column('entrypoints', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('default_entrypoint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_hash'), 'packages', ['hash'], unique=False)
    op.create_table('processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('script_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entrypoint_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_entrypoint_name'), 'processes', ['entrypoint_name'], unique=False)
    op.create_index(op.f('ix_processes_name'), 'processes', ['name'], unique=True)
    op.create_table('queue_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('locked_by_robot_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_items_queue_id'), 'queue_items', ['queue_id'], unique=False)
    op.create_index('ix_queue_items_queue_id_status', 'queue_items', ['queue_id', 'status'], unique=False)
    op.create_index(op.f('ix_queue_items_reference'), 'queue_items', ['reference'], unique=False)
    op.create_table('queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('enforce_unique_reference', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queues_external_id'), 'queues', ['external_id'], unique=True)
    op.create_index(op.f('ix_queues_name'), 'queues', ['name'], unique=True)
    op.create_table('robots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_heartbeat', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('current_job_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('machine_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credential_asset_id', sa.Integer(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('api_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robots_credential_asset_id'), 'robots', ['credential_asset_id'], unique=False)
    op.create_index(op.f('ix_robots_machine_id'), 'robots', ['machine_id'], unique=False)
    op.create_index(op.f('ix_robots_name'), 'robots', ['name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('artifact', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_permissions_artifact'), 'role_permissions', ['artifact'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('sdk_auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('machine_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sdk_auth_sessions_created_at'), 'sdk_auth_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_sdk_auth_sessions_expires_at'), 'sdk_auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sdk_auth_sessions_machine_name'), 'sdk_auth_sessions', ['machine_name'], unique=False)
    op.create_index(op.f('ix_sdk_auth_sessions_session_id'), 'sdk_auth_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_sdk_auth_sessions_status'), 'sdk_auth_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_sdk_auth_sessions_user_id'), 'sdk_auth_sessions', ['user_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_index(op.f('ix_settings_updated_at'), 'settings', ['updated_at'], unique=False)
    op.create_table('triggers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('TIME', 'QUEUE', name='triggertype'), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('robot_id', sa.Integer(), nullable=True),
    sa.Column('cron_expression', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_fired_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('next_fire_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.Column('polling_interval', sa.Integer(), nullable=True),
    sa.Column('last_processed_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_enabled'), 'triggers', ['enabled'], unique=False)
    op.create_index(op.f('ix_triggers_name'), 'triggers', ['name'], unique=False)
    op.create_index(op.f('ix_triggers_process_id'), 'triggers', ['process_id'], unique=False)
    op.create_index(op.f('ix_triggers_queue_id'), 'triggers', ['queue_id'], unique=False)
    op.create_index(op.f('ix_triggers_robot_id'), 'triggers', ['robot_id'], unique=False)
    op.create_index(op.f('ix_triggers_type'), 'triggers', ['type'], unique=False)
    op.create_index('ix_triggers_type_enabled', 'triggers', ['type', 'enabled'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('organization', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index('ix_triggers_type_enabled', table_name='triggers')
    op.drop_index(op.f('ix_triggers_type'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_robot_id'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_queue_id'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_process_id'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_name'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_enabled'), table_name='triggers')
    op.drop_table('triggers')
    op.drop_index(op.f('ix_settings_updated_at'), table_name='settings')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_sdk_auth_sessions_user_id'), table_name='sdk_auth_sessions')
    op.drop_index(op.f('ix_sdk_auth_sessions_status'), table_name='sdk_auth_sessions')
    op.drop_index(op.f('ix_sdk_auth_sessions_session_id'), table_name='sdk_auth_sessions')
    op.drop_index(op.f('ix_sdk_auth_sessions_machine_name'), table_name='sdk_auth_sessions')
    op.drop_index(op.f('ix_sdk_auth_sessions_expires_at'), table_name='sdk_auth_sessions')
    op.drop_index(op.f('ix_sdk_auth_sessions_created_at'), table_name='sdk_auth_sessions')
    op.drop_table('sdk_auth_sessions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_artifact'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_robots_name'), table_name='robots')
    op.drop_index(op.f('ix_robots_machine_id'), table_name='robots')
    op.drop_index(op.f('ix_robots_credential_asset_id'), table_name='robots')
    op.drop_table('robots')
    op.drop_index(op.f('ix_queues_name'), table_name='queues')
    op.drop_index(op.f('ix_queues_external_id'), table_name='queues')
    op.drop_table('queues')
    op.drop_index(op.f('ix_queue_items_reference'), table_name='queue_items')
    op.drop_index('ix_queue_items_queue_id_status', table_name='queue_items')
    op.drop_index(op.f('ix_queue_items_queue_id'), table_name='queue_items')
    op.drop_table('queue_items')
    op.drop_index(op.f('ix_processes_name'), table_name='processes')
    op.drop_index(op.f('ix_processes_entrypoint_name'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_packages_hash'), table_name='packages')
    op.drop_table('packages')
    op.drop_index(op.f('ix_machines_name'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_jobs_trigger_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_source'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_execution_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_execution_logs_timestamp'), table_name='job_execution_logs')
    op.drop_index(op.f('ix_job_execution_logs_level'), table_name='job_execution_logs')
    op.drop_index('ix_job_execution_logs_job_execution_id_timestamp', table_name='job_execution_logs')
    op.drop_index('ix_job_execution_logs_job_execution_id_level', table_name='job_execution_logs')
    op.drop_index(op.f('ix_job_execution_logs_job_execution_id'), table_name='job_execution_logs')
    op.drop_index(op.f('ix_job_execution_logs_created_at'), table_name='job_execution_logs')
    op.drop_table('job_execution_logs')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_asset_name'), table_name='asset')
    op.drop_table('asset')
    # ### end Alembic commands ###
